global:
  scrape_interval: 15s

scrape_configs:
  - job_name: identity
    static_configs:
      - targets: ["identity:8000"]
  - job_name: connectivity
    static_configs:
      - targets: ["connectivity:8000"]
  - job_name: knowledge
    static_configs:
      - targets: ["knowledge:8000"]
  - job_name: experience
    static_configs:
      - targets: ["experience:8000"]
  - job_name: automation
    static_configs:
      - targets: ["automation:8000"]
